### ISSUE TITLE
OS X でmd5sumがないので checker/run.sh に弾かれる

### ISSUE THREAD

**Issue by dominion525** [kokuyouwind/escape-from-the-repository#5]
OSXは標準では `md5sum` が入っていません。

ので、Homebrew で `$ brew install md5sha1sum` とする必要がありますが、`$ openssl md5 FILE_NAME`のようにすればプラットフォームに関わらず利用できていいのではないでしょうか。

**Comment by kokuyouwind** [comment]
この件については、当初opensslコマンドでの実装としていたものの、opensslコマンドの出力形式に方言がありうまく動かない場合があったことからmd5sumを利用する形としています。
また、md5sumが必要である旨とインストール方法はREADMEに記述してあり、check/run.shでもインストールを促すことから、現行のままにしたいと思います。
